# Generated by Django 6.0.1 on 2026-02-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('students', '0002_studentcorrectionrequest_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='selected_students',
            field=models.ManyToManyField(blank=True, related_name='selected_jobs', to='students.student'),
        ),
    ]
