# Generated by Django 6.0.1 on 2026-03-24 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_selected_students'),
        ('students', '0002_studentcorrectionrequest_is_read_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='selected_students',
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.TextField(default=0, help_text='Comma separated skills'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlacementSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField()),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
