# Generated by Django 6.0.1 on 2026-02-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcorrectionrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='studentcorrectionrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Read', 'Read'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentcorrectionrequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correction_requests', to='students.student'),
        ),
    ]
