# Generated by Django 6.0.1 on 2026-02-11 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('COLLEGE', 'Institution Admin'), ('STUDENT', 'Student')], default='STUDENT', max_length=20),
        ),
    ]
